name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Code Quality Check"]
    types:
      - completed
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  NODE_VERSION: "18.17.0"
  PM2_APP_NAME: "nextjs"

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy to VPS
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.workflow_run.head_branch }}

    concurrency:
      group: deploy-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: true

    steps:
      - name: Verify Secrets Configuration
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "::error::SSH_PRIVATE_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VPS_HOST }}" ]; then
            echo "::error::VPS_HOST is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VPS_USER }}" ]; then
            echo "::error::VPS_USER is not set"
            exit 1
          fi
          if [ -z "${{ secrets.PROJECT_PATH }}" ]; then
            echo "::error::PROJECT_PATH is not set"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH Setup
        run: |
          echo "Testing SSH agent configuration..."
          ssh-add -l
          echo "Testing connection to GitHub..."
          ssh -T git@github.com || true
          echo "Testing connection to VPS..."
          ssh -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} || true

      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Debug Environment Variables
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Workflow run branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Checking if variables are set:"
          [[ -n "${{ secrets.PROJECT_PATH }}" ]] && echo "PROJECT_PATH is set" || echo "PROJECT_PATH is empty"
          [[ -n "${{ secrets.VPS_USER }}" ]] && echo "VPS_USER is set" || echo "VPS_USER is empty"
          [[ -n "${{ secrets.VPS_HOST }}" ]] && echo "VPS_HOST is set" || echo "VPS_HOST is empty"

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: ${{ secrets.PROJECT_PATH }}
          NODE_ENV: production
          DEPLOY_USER: ${{ secrets.VPS_USER }}
          DEPLOY_HOST: ${{ secrets.VPS_HOST }}
          DEPLOY_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          # Create deployment script
          cat << 'EOF' > deploy.sh
            set -e  # Exit on any error
            
            echo "Environment variables:"
            echo "DEPLOY_PATH: ${DEPLOY_PATH}"
            echo "DEPLOY_BRANCH: ${DEPLOY_BRANCH}"
            echo "DEPLOY_USER: ${DEPLOY_USER}"
            echo "DEPLOY_HOST: ${DEPLOY_HOST}"
            
            echo "🚀 Starting deployment for branch ${DEPLOY_BRANCH}..."
            
            # Test git and directory permissions
            if [ ! -w "$(dirname ${DEPLOY_PATH})" ]; then
              echo "Error: No write permission to ${DEPLOY_PATH}"
              exit 1
            fi
            
            if [ -d "${DEPLOY_PATH}/.git" ]; then
              cd ${DEPLOY_PATH}
              echo "📥 Pulling latest changes..."
              git fetch origin ${DEPLOY_BRANCH}
              git reset --hard origin/${DEPLOY_BRANCH}
            else
              echo "🔄 Cloning repository..."
              rm -rf ${DEPLOY_PATH}
              git clone -b ${DEPLOY_BRANCH} git@github.com:galaonlinehub/gala_education_website.git ${DEPLOY_PATH}
              cd ${DEPLOY_PATH}
            fi

            # Backup current .env file if it exists
            if [ -f .env ]; then
              cp .env .env.backup
            fi
            
            echo "📦 Installing dependencies..."
            npm ci --production
            
            # Restore .env file
            if [ -f .env.backup ]; then
              mv .env.backup .env
            fi
            
            echo "🏗️ Building application..."
            npm run build
            
            echo "🧹 Clearing Next.js cache..."
            rm -rf .next/cache
            
            echo "🔄 Restarting PM2 process..."
            if pm2 list | grep -q "${PM2_APP_NAME}"; then
              pm2 reload ${PM2_APP_NAME} --update-env
            else
              pm2 start npm --name "${PM2_APP_NAME}" -- start
            fi
            
            echo "✅ Deployment completed successfully!"
          EOF

          # Make script executable
          chmod +x deploy.sh

          # Debug: Show script content
          echo "Deployment script content:"
          cat deploy.sh

          # Copy and execute script on remote server
          scp -v ./deploy.sh $DEPLOY_USER@$DEPLOY_HOST:/tmp/deploy.sh
          ssh -v $DEPLOY_USER@$DEPLOY_HOST "bash /tmp/deploy.sh"

          # Cleanup
          ssh $DEPLOY_USER@$DEPLOY_HOST "rm /tmp/deploy.sh"

      - name: Verify Deployment
        run: |
          echo "🔍 Verifying deployment..."
          sleep 10  # Wait for service to start
          curl --fail --silent --head ${{ secrets.APP_URL }} || (echo "❌ Deployment verification failed" && exit 1)
          echo "✅ Deployment verified successfully!"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "::error::Deployment failed! Please check the logs for more details."